# Generated by Django 4.1.4 on 2022-12-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkcategory',
            old_name='drink_category_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='drink_name',
            new_name='drink',
        ),
        migrations.AddField(
            model_name='drinks',
            name='category_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.drinkcategory'),
        ),
    ]
