# Generated by Django 4.1.4 on 2022-12-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_drink_category_name_drinkcategory_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(help_text='Enter email address', max_length=254)),
                ('time_log', models.TimeField(help_text='Enter the exact time')),
            ],
        ),
    ]
