# Generated by Django 4.1.4 on 2022-12-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='DrinkCategory',
        ),
    ]
